### PR TITLE
Fix crashing CI

### PR DESCRIPTION
**Pull request by Skydes**
- COLMAP recently switched to Metis: https://github.com/colmap/colmap/commit/29a1e3642a3b00734a52b21e597ea4d576485fe6
- Running the CI on every branch creation is unnecessary

### CODE REVIEW

**Comment by johnwlambert** [comment]
Hi @Skydes, thanks for the PR. It looks like the `brew install` of `metis` is appropriately installing the dependencies, but on linux, the `metis` library is not found. Is this what you're seeing? I suppose we may need to pass a flag like `METIS_INCLUDE_DIRS`?

**Comment by johnwlambert** [comment]
I'm seeing:
```
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.vcea.wsu.edu
 * centos-sclo-rh: repo1.sea.innoscale.net
 * epel: mirrors.kernel.org
 * extras: sjc.edge.kernel.org
 * updates: mirror.web-ster.com
No package build-essential available.
Error: Not tolerating missing names on install, stopping.
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.vcea.wsu.edu
 * centos-sclo-rh: repo1.sea.innoscale.net
 * epel: mirrors.kernel.org
 * extras: sjc.edge.kernel.org
 * updates: mirror.web-ster.com
 ```
 on the yum install, so `yum` isn't installing anything, perhaps

**Comment by Skydes** [comment]
It seems that yum fails on most package installs, currently looking into this.

**Comment by Skydes** [comment]
@johnwlambert I cleaned up the yum installs. It previously failed to install suitesparse for Ceres.

**Review by Phil26AT — APPROVED** [review]

**Pull request merged**
